services:
  - type: web
    name: swiggy-concierge
    env: node
    plan: free
    buildCommand: npm install && npx prisma generate && npx prisma migrate deploy && npm run build && npm run seed
    startCommand: npm start
    repo: https://github.com/Saurav1603/Swiggy_App
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
    healthCheckPath: /api/health/socket
    autoDeploy: true
